version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/xrizur/data/certbot/www:/var/www/certbot/:ro
      - /home/xrizur/data/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - flask
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${HOME}/data/certbot/www/:/var/www/certbot/:rw
      - ${HOME}/data/certbot/conf/:/etc/letsencrypt/:rw
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    env_file:
      - .env
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app:create_app()"
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    networks:
      - my-network
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3306:3306
    env_file:
      - .env
    volumes:
      - /home/xrizur/data/mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
    name: my-network