version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: unless-stopped
    ports:
      - '8081:8081'

    volumes:
      - '${HOME}/data/jenkins_data:/bitnami/jenkins'
      - '${HOME}/data/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_data:
    driver: local
  jenkins_home:
    driver: local