version: '3'
services:
  jenkins:
    image: 'santhoshkdhana/jenkins-python3.9'
    restart: unless-stopped
    ports:
      - '8080:8080'

    volumes:
      - 'jenkins_data:/bitnami/jenkins'
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  jenkins_data:
    driver: local
  jenkins_home:
    driver: local