version: '3'
services:
  jenkins:
    image: 'jenkins'
    restart: unless-stopped
    ports:
      - '8080:8080'

    volumes:
      - '${HOME}/data/jenkins_data:/bitnami/jenkins'
      - '${HOME}/data/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_data:
    driver: local
  jenkins_home:
    driver: local